# Generated by Django 6.1.1 on 2026-09-22 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('fetching', 'Сбор источников'), ('analyzing', 'Анализ кандидатов'), ('completed', 'Готово'), ('partial', 'Готово с ошибками источников'), ('failed', 'Ошибка')], default='queued', max_length=16)),
                ('processed_sources', models.PositiveIntegerField(default=0)),
                ('candidates_count', models.PositiveIntegerField(default=0)),
                ('weak_signals_count', models.PositiveIntegerField(default=0)),
                ('high_confidence_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('potential_benefit', models.TextField(blank=True)),
                ('case_example', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0)),
                ('is_weak_signal', models.BooleanField(default=False)),
                ('is_high_confidence', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('factors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='pipeline.searchrun')),
                ('source_documents', models.ManyToManyField(related_name='candidates', to='parser.sourcedocument')),
            ],
            options={
                'ordering': ['-confidence', 'title'],
                'indexes': [models.Index(fields=['run', 'is_weak_signal', 'confidence'], name='pipeline_te_run_id_1ff56a_idx')],
            },
        ),
    ]
