# Generated by Django 6.1.1 on 2026-09-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=512)),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=32)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('trust', models.FloatField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
