# Generated by Django 6.1.1 on 2026-09-22 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parser', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pipeline.searchrun'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['run', 'provider'], name='parser_sour_run_id_c3bdf5_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['published_date'], name='parser_sour_publish_3484f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(fields=('run', 'provider', 'external_id'), name='unique_document_per_run'),
        ),
    ]
